### ISSUE TITLE
Pass github secrets to the bicep template

### ISSUE THREAD

**Issue by bahramr** [Azure/arm-deploy#203] opened 2024-05-01 17:12 UTC
This example in the README does not work when using bicep templates: https://github.com/Azure/arm-deploy?tab=readme-ov-file#example

For some reasons the bicep parameters specified are not overridden when using secrets, here is my code:

name: Deploy Bicep template
uses: azure/arm-deploy@v1
with:
  scope: resourcegroup
  subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
  resourceGroupName: "rg-contoso"
  template: ./main.bicep
  parameters: ./main.parameters.bicepparam adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ 
  secrets.ADMINPASSWORD }}
  failOnStdErr: false

**Comment by anthony-c-martin** [comment] 2024-05-02 00:22
Closing as I believe this is a duplicate of #139.

There's an underlying issue with Azure CLI that'll be fixed with https://github.com/Azure/azure-cli/pull/28826. Until then, please take a look at the workaround suggested under #139.

**Closed by anthony-c-martin** 2024-05-02 00:22 UTC
Labels: Needs: Triage :mag:
